language: java
jdk:
  - openjdk11

before_install: "curl --create-dirs -o target/travis/settings.xml https://gist.githubusercontent.com/kaspernielsen/f02d81dd42d5acc5aa02/raw/fd5cb0b349beb214c360d10244b009654e5cb08c/settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"

# whitelist
branches:
  only:
    - master

# we need to cd modules, because the coveralls plugin is defined in modules/pom.xml, with a depdency on jaxb
after_success:
  - cd modules
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report

env:
  global:
    - secure: "0p8irieo+7T9FMrrhbrgjIsExgcf3jYM5FgTqoVm7icfKzzFLBWn/tm02MzEEHn5UUjD3Dz/70t1XyIwmHEDsu89kYnKMUkYzQITjQOMOKibA48O/Z//5euviTCK5mhcMXkh54htZ6C80YQ2wckLtDzibmdo+FVNL5IV5SJbxdcepq1ymLOSzjrnxSi3n9DOdVuO0zB99+arRH6+bvSJN+m2DanharxL4lzcaCmmILkrlNZ3dIEqX/7ATiBH07sQglvDAlTy16IE1iv4Bxfu3jsr8oKM4Tf1Cbg9H6yQ3oLAMV79nli32MiFSe+SJoWy71SPzrwGIsp4YzSO6Vp337XCgh5c5F25yRyJN8BVMomqLiptRjgAhcevQb/0Klzc09BrfNT4Bht1M1odRc4j2YNeKzAJ2dFqY12tu4TylCqJbe0SbbztZFzNRdxbC2yX3aPHC/PuY0TesK8W9XW90o7HiHWGhRPIKz6yoXN12dUA8rc1honX2OblANouBACGfVPANtGyz/Dk3ncUOcThUIEVeo3IbaruegXEzpLhKFXlAF+0m0YFd3gybwNJy50PEVVTDF4NjJrpEW0AKq74Alt+YcV8g5NnAxwJi0ccXZtGw9AyoEmaSGfzX0qa0uyD+QQ6uw0WFEEl4gtK3BBBt2nAHS+oAElz+2H1re7kCEs="
    - secure: "7O+odkIIrzqvbkNngFZ/dX9j27xNt/nvkdaYZsOI2fY2ckoC0OtW9aPJTNnZ0z4s8syAGJiD6n+zFYxYqQr9aSInoavuMkaanOKHCClaGk7kl2MtpdPp+MB04X1JNfd7xNjf/7JABI56cBoChvMPj9IDF90oLnknS2/3wAusTfTCgycmK1plofE1rgI9wDnWRqew+GYhFqwOojcDF1MfvS8RL/Ecz/RNjQa1rMWayqKM89ESvb6ES75LkfeSTAtiwdQOdz49IfiV8wGYTBauLgc8eAiempSobqLejMj12M6EONtSfumT6SX7h6DM5LZ3j8eMo/rTKTNitD4932uPbsTCQAxQ/I1HSOjIwDifhVX1h6DyLEixRaZKIV7QXv6XK4adFYTiXTintKSWrHkITYz/kR1UjUhOXYZJgSPnHENIz+s1BPZPUeNyGATL3f4BUZ9oBrU/kPliZomreLX3duKZopCVpxu2xlaFmICsgNCvimlKafZEKZxa0gqwf2hUz7yxBr/YRo/nJawkaTiuQjiykiAv/JsOFR1gJcGyXGg+e7zywLPcEDgK/DMJDc37Ycr4Di3pUXIaxK41d7rUhnjGP5vctRih5qItvyqXzgzoQhSwXyAMUyfK4UeT5Pr9aWG+wtHvRKLkm9QX3335n8zRQmVcueqxKmtKdM5pltU="
     